### ISSUE TITLE
Can we add SCSI Controllers and assigning hard disks to SCSI Controllers? 

### ISSUE THREAD

**Issue by amitbhadra** [hashicorp/terraform-provider-vsphere#1121]
From the vSphere UI, I can add "New SCSI Controller". My use case is to create 4 SCSI Controllers. And when I create a new hard disk, I want to assign each hard disk to some SCSI Controller.

So essentially, suppose I have 8 hard disks and 4 SCSI Controllers, and I want to add Hard disks 1 and 2 to SCSI 0 as 0:0 and 0:1, Hard disks 3 and 4 to SCSI 1 as 1:0 and 1:1, etc. This isn't evident in the documentation. Is this possible?

**Comment by bish0polis** [comment]
Yeah, I'm spreading a whack of disks through 4 different pvscsi adaptors, so some get SSD, some get DAS and some get NAS.  You can target your different adapters as well as pick a unit number like you want.

terraform-0.12.28-1.el7.harbottle.x86_64
golang-github-terraform-provider-vsphere-1.13.0-0.1.x86_64

I'm not sure how old those packages are, but I've been doing it since just after 012 came out.

**Comment by dhekimian** [comment]
Once you create the controllers, all you need to do is assign the disks the unit number to get it into the slot you want. 

https://www.terraform.io/docs/providers/vsphere/r/virtual_machine.html#unit_number

Take a look at this comment to see an example: https://github.com/hashicorp/terraform-provider-vsphere/issues/997#issuecomment-598976061

scsi0:0-14 are unit numbers 0-14
scsi1:0-14 are unit numbers 15-29
scsi2:0-14 are unit numbers 30-44
scsi3:0-14 are unit numbers 45-59
