### ISSUE TITLE
Allow guest_id to be empty when vmware tools is not installed

### ISSUE THREAD

**Issue by lmayorga1980** [hashicorp/terraform-provider-vsphere#1206]
### Description

I have imported a self-contained OVA file from a vendor and would like to replicate the number of instances using the vsphere-provider. we DO NOT have access to the operating system directly but the vendor claims that the vmware tools are installed and compatible with our current ESX version 6.7.

The OVA was imported as a VM Template(In the Console VMWare show no Vmware Tools installed). A new instance can be created from the GUI but with Terraform it complains about the Guest Operating System.

`Error: error sending customization spec: Customization of the guest operating system 'ubuntu64Guest' is not supported in this configuration. Microsoft Vista (TM) and Linux guests with Logical Volume Manager are supported only for recent ESX host and VMware Tools versions. Refer to vCenter documentation for supported configurations.`

In this scenario, we DO NOT have access to customize the OS behind our vendor self-contained VM and that means no updated `vmware-tools`.

### Potential Terraform Configuration

```
resource "vsphere_virtual_machine" "delphix" {
  name             = "delphix"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  guest_id = "ubuntu64Guest"
  scsi_type = data.vsphere_virtual_machine.template.scsi_type
  num_cpus  = 4
  memory    = 20

  network_interface {
    network_id = data.vsphere_network.network.id
  }

...
```

During the creation of a new vm from my imported VM Template I was able to create an instance without any customizations(as-is from the vendor) and the instance is created successfully. With Terraform, I am forced to set a Guest Id. 

![Screen Shot 2020-09-09 at 6 23 03 PM](https://user-images.githubusercontent.com/3172378/92660972-83b13b00-f2c9-11ea-8634-d47953945b3e.png)

**Comment by dhekimian** [comment]
In my experience this could be because VMware Tools hasn’t added the properties to the .vmx file yet to say if its installed and what version, etc. Powering the VM on so VMware Tools can run and then shutting it down usually does the trick.

Look at the .vmx settings for the imported and compare it to the powered on .vmx to see if you can identify the correct settings and try to add them to the powered off VM. 

You’ll need to reload the .vmx settings into vCenter to get it to take effect if you edit the .vmx settings from the command line.

1. Run `vim-cmd vmsvc/getallvms` to get the vmid
2. Run `vim-cmd vmsvc/reload [vmid]` to reload it

**Comment by lmayorga1980** [comment]
I did `Power On` the VM from the Console and the VM comes online fine and `Powered Off` as well and seems like the vmware-tools seems to be detected.


![Screen Shot 2020-09-10 at 9 16 50 AM](https://user-images.githubusercontent.com/3172378/92742503-aedd6e00-f34d-11ea-8b5a-c0486a78a93c.png)

I had to set this attribute manually instead of the default inherit from the template.

`guest_id = "ubuntu64Guest"`
