### ISSUE TITLE
80 character name limit is invalid when using `d/virtual_machine`

### ISSUE THREAD

**Issue by barbaricprogrammer** [hashicorp/terraform-provider-vsphere#1262]
The paths passed to 'data "vsphere_virtual_machine"' are often longer than the 80 character name limit.

Either relax this limit specified: https://github.com/hashicorp/terraform-provider-vsphere/blob/3b1d5a379663f08f37a65b7d3c1406baad3c4259/vsphere/virtual_machine_config_structure.go#L183

OR provide a way to specify the folder when getting the data item.

**Comment by Alucard616** [comment]
Is something happening here?
I also have this problem.

**Comment by lindhe** [comment]
Until this is fixed, it should at least be added to the documentation! It's never fun to learn the hard way. 😕

**Comment by lindhe** [comment]
@vancluever it seems like you introduced this limitation in https://github.com/hashicorp/terraform-provider-vsphere/commit/a7011abfb4f9e1fd682363fa2058d0d865658d52. Do you recall if it was introduced for a good reason? Do we need to find a way to work around this issue, or can the limit of max 80 characters be relaxed/removed?

**Comment by lindhe** [comment]
If we must keep the limit for the `name` field, I think we should introduce a new field `folder` to work around this limitation. I think that could be done without it being a breaking change.

It could look like this:

```hcl
data "vsphere_virtual_machine" "template" {
  name          = "foo"
  folder        = "/DC1/vm/bar"
  datacenter_id = data.vsphere_datacenter.datacenter.id
}
```

I like this solution, because it is similar in design to the `vsphere_virtual_machine` _resource_ that already has a `folder` field: https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/resources/virtual_machine#folder

@tenthirtyam what do you think?
