### ISSUE TITLE
OS family for guest ID "windows2019srv_64Guest": could not find guest ID "windows2019srv_64Guest"

### ISSUE THREAD

**Issue by bpfoley45** [hashicorp/terraform-provider-vsphere#1332]
### Terraform Version

Terraform v0.14.6

### vSphere Provider Version

vsphere v1.24.3

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### Expected Behavior

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

### Actual Behavior

Error: cannot find OS family for guest ID "windows2019srv_64Guest": could not find guest ID "windows2019srv_64Guest"

  on instance.tf line 29, in resource "vsphere_virtual_machine" "vm":
  29: resource "vsphere_virtual_machine" "vm" {

### Steps to Reproduce

Create OVF manually or with packer and import into content library for Windows Server 2019 with default guest_os_type

data "vsphere_content_library" "library" {
  name = "Templates"
}
data "vsphere_content_library_item" "item" {
  name       = "Template-Win2019-GUI-CloudInit-Current"
  library_id = data.vsphere_content_library.library.id
  type = "OVF"
}

terraform apply

### Important Factoids

attempting to set the guest_id to anything else in the resource "vsphere_virtual_machine" does not help

  guest_id = "windows9Server64Guest"

### References

* #0000

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by toaarif** [comment]
I am trying to deploy a Windows 2016 server from template using the VSphere provider but I am also getting the same issue (_Error: cannot find OS family for guest ID "windows2019srv_64Guest": could not find guest ID "windows2019srv_64Guest_"). 
Is there any workaround or solution is available ?  Any help would be greatly appreciated .Thanks

**Comment by tenthirtyam** [comment]
One critically important piece of information is missing from the issue description is which version of vSphere is being used in the environment? The would help to ensure that the version of vSphere in the environment fully supports Windows 2019 as a guest OS since the it appears `windows2019srv_64Guest` is not being allowed.

With regards to Windows 2016, the value would be `windows9Server64Guest`.

Ryan

**Comment by tenthirtyam** [comment]
Hi @bpfoley45,  checking in to see if you can comment on the vSphere version and if this issue still exists for you - or if it can e closed?

Ryan

**Comment by tenthirtyam** [comment]
Hi @bpfoley45, checking in to see if you can comment on the vSphere version and if this issue still exists for you - or if it can e closed?

Ryan

**Comment by tenthirtyam** [comment]
Hi @bpfoley45,

I'm marking this issue as closed based on the comments and testing provided earlier in the thread. 

One critically important piece of information that was missing from the issue description is which version of vSphere is being used in the environment. This would help to ensure that the version of vSphere in the environment fully supports Windows 2019 as a guest OS since it appears `windows2019srv_64Guest` is not being allowed and is dependent on the vSphere version.

With regards to Windows 2016 (mentioned by @toaarif), the value would be `windows9Server64Guest`.

If the issue persists with the latest version, please open a new issue and reference this originating issue. The updated bug template now includes the request for the vSphere version.

**Ryan Johnson**
Staff II Solutions Architect, VMware, Inc.
