### ISSUE TITLE
Add support for setting router advertise for IPv6

### ISSUE THREAD

**Issue by maxadamo** [hashicorp/terraform-provider-vsphere#1385]
### Description

Allow Netplan to disable Router Adertisment for IPv6

### Potential Terraform Configuration

N/A

### References

Netplan has a parameter called `accept-ra:` which allows to disable/enable router advertisement and it accepts booleans (`true`, `false`, `yes`, `no`) as follows:

`accept-ra: false `

Does this parameter exist in terraform and it's not documented or is it missing?

**Comment by tenthirtyam** [comment]
Hi @maxadamo, this would be an `enhancement` (#1280) versus a `bug`. 

Today, native vSphere guest customizations do not support this option; however, it _**might**_ be be possible to address _**if**_ support for the customization script (_as seen in customization specifications_) was added to `linux_options` similar to the run commands for Windows - in lieu of the native support vSphere.

Another option is to determine if the latest versions of `cloud-init` may serve the purpose and if so, use the `extra_config` arg instead of `linux_options`.

Ryan

**Comment by tenthirtyam** [comment]
Similar to #1557 in terms of potential enhancement (customization script) and use of cloud-init.

Marking this one as closed to track in the latest issue.
