### ISSUE TITLE
Add support for attaching tags to ESXi hosts

### ISSUE THREAD

**Issue by doumhfr** [hashicorp/terraform-provider-vsphere#1452]
### Description

vsphere_host doesn't seem to support tag assignement 

 Error: Unsupported argument
│ 
│   on host.tf line 17, in resource "vsphere_host" "host1":
│   17:   tags = [
│ 
│ An argument named "tags" is not expected here.

### Potential Terraform Configuration

```hcl
resource "vsphere_host" "host1" {
  hostname = "host1.domain.local"
  username = "root"
  password = ""
  cluster  = vsphere_compute_cluster.cluster1.id
  tags = [
    vsphere_tag.tagname.id,
    ]
}

```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by bloudraak** [comment]
This is my use case. I'm using Packer to create templates. In order to provide it with the correct resources to use when creating those templates, I tag the resources with `Packer` with the category `Automation`. I then use PowerCLI to find the respective resources, generate a `variables.json` file, and call Packer. After Packer is done, I take the virtual machine, convert it to a template, tag it and add some custom attributes. 

Later in another CI/CD process, I look for templates that have certain tags and custom attributes, sort them by the date they were created, and subsequently create virtual machines from them. 

At this moment, I have to use PowerCLI to fill the gap.
