### ISSUE TITLE
ignore external pvc disks, which are not in the terraform config

### ISSUE THREAD

**Issue by c0razo** [hashicorp/terraform-provider-vsphere#1465]
version:
vsphere provider 1.22.0
terraform: 0.12.28

if i am running terraform plan even without changes in the code, it will change the labels of the pvc disks from the kubernetes worker nodes. changing the label forces the disk to recreate (by documentation). this causes workload not work anymore.

does anybody have the same problem or a workaround?
adding "disk" to lifecycle changes doesnt work and is not an option as well, because we are working with a custom vm module used in another configs as well.

![image](https://user-images.githubusercontent.com/74508567/128488386-00af7fd3-f93d-4f77-88e8-fa64b0f4c5ac.png)

**Comment by Calvinaud** [comment]
Hello,

Your issue is also related to <https://github.com/hashicorp/terraform-provider-vsphere/issues/750>. In this issue, just like you said, they ignore all *disk* section.

I also have the same problem that we couldn't ignore every *disk*.  I didn't find a clear workaround but I used this solution (which is not very clean):

```hcl
ignore_changes = [
    disk[3], disk[4], disk[5] ... disk[6]
]
```

I manually ignored each disk after the first 3 disks (I automated the process with a sed during the pipeline). It work only if you have a constant number of *disk* to ignore.


Another solution, **which is not possible for the moment**, that may be possible is to check the name of all the disks on a VM and ignore those specifics disks:

```hcl
 ignore_changes =[
       for index, disk in vsphere_virtual_machine.vm.disk:
          "disk[${index}]" if length(regexall("orphaned_disk_*", disk.name)) > 0
    ]
```

But it's not actually possible since lifecycle only accepts literals values for the moment: <https://github.com/hashicorp/terraform/issues/24188>.


If anyone have a better solution I am also interested.

**Comment by c0razo** [comment]
> Hello,
> 
> Your issue is also related to #750. In this issue, just like you said, they ignore all _disk_ section.
> 
> I also have the same problem that we couldn't ignore every _disk_. I didn't find a clear workaround but I used this solution (which is not very clean):
> 
> ```terraform
> ignore_changes = [
>     disk[3], disk[4], disk[5] ... disk[6]
> ]
> ```
> 
> I manually ignored each disk after the first 3 disks (I automated the process with a sed during the pipeline). It work only if you have a constant number of _disk_ to ignore.
> 
> Another solution, **which is not possible for the moment**, that may be possible is to check the name of all the disks on a VM and ignore those specifics disks:
> 
> ```terraform
>  ignore_changes =[
>        for index, disk in vsphere_virtual_machine.vm.disk:
>           "disk[${index}]" if length(regexall("orphaned_disk_*", disk.name)) > 0
>     ]
> ```
> 
> But it's not actually possible since lifecycle only accepts literals values for the moment: [hashicorp/terraform#24188](https://github.com/hashicorp/terraform/issues/24188).
> 
> If anyone have a better solution I am also interested.

Hey @Calvinaud 

thank you so much! This helped.
I owe you.

Have a good one!

Wbr
