### ISSUE TITLE
Datacenter id mismatch.

### ISSUE THREAD

**Issue by indreek** [hashicorp/terraform-provider-vsphere#1471]
### Terraform Version
1.0.5

### vSphere Provider Version
2.0.2

### Terraform Configuration Files

```hcl
resource "vsphere_datacenter" "srv1" {
  name = "SRV1"
  tags = [
    vsphere_tag.k8s_region_srv1.id
  ]
}

data "vsphere_datacenter" "dc" {
  name = "SRV1"
}

resource "vsphere_compute_cluster" "srv1_prod" {
  name            = "srv1_prod"
  datacenter_id   = vsphere_datacenter.srv1.id
}
```

### Expected Behavior

vsphere_datacenter data and resource objects to have same id output.

### Actual Behavior

If i use data.vsphere_datacenter.srv1.id it gets correct datacenter id "datacenter-2". If i use resource vsphere_datacenter.srv1.id the id is "SRV1" and it forces replacement.

**Comment by tenthirtyam** [comment]
@indreek - it should be done similar to as follows so that the `vsphere_datacenter` ID (`moref`) can be returned from the data source and then passed to the resource `vsphere_compute_cluster`.

```hcl
data "vsphere_datacenter" "srv1" {
  depends_on = [
    vsphere_datacenter.srv1
  ]
  name = "srv1"
}

resource "vsphere_datacenter" "srv1" {
  name = "srv1"
}

resource "vsphere_compute_cluster" "srv1_prod" {
  name            = "srv1_prod1"
  datacenter_id   = data.vsphere_datacenter.srv1.id
}
```

Of course, if you want to do this with the tags, then it would look similar to the following. Note that I put in the `depends_on` to help ensure the order of operations.

```hcl
resource "vsphere_tag" "k8s_tag" {
  name        = "k8s"
  category_id = vsphere_tag_category.k8s_tag_category.id
  description = "k8s"
}

data "vsphere_datacenter" "srv1" {
  depends_on = [
    vsphere_datacenter.srv1,
    vsphere_tag_category.k8s_tag_category,
    vsphere_tag.k8s_tag
  ]
  name = "srv1"
}

resource "vsphere_datacenter" "srv1" {
  name = "srv1"
  tags = [ "k8s" ]
}

resource "vsphere_compute_cluster" "srv1_prod" {
  name            = "srv1_prod1"
  datacenter_id   = data.vsphere_datacenter.srv1.id
}
```

Hope that helps.

Ryan
@tenthirtyam

Recommend: `close/not-a-bug`
