### ISSUE TITLE
Ignore changes to VM Clone Template UUID

### ISSUE THREAD

**Issue by rene-at-dell** [hashicorp/terraform-provider-vsphere#1474]
### Description

Long lived assets could need to have resources changes (CPU, RAM, etc.) but need to avoid the VM to be recreated if the original template has changed or has been deleted.

### Potential Terraform Configuration

```hcl
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
    template_ignore_changes = true
  }
```

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

**Comment by tenthirtyam** [comment]
@rene-at-dell 

This is already possible with the lifecycle meta-argument in Terraform. 

Below are two examples:

```hcl:
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  lifecycle {
    ignore_changes = [
      clone,
    ]
  }
```

or 

```hcl:
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
```

Ryan

Recommend: `close/not-an-enhancement`

**Comment by zenhighzer** [comment]
- I like the idea of having something like "template_ignore_changes = true"
- lifecycle {....} looks ugly
- we have the same challenge to not recreate our running machines but also be able to update our source-templates with the same template-name.. and to be honest: we really dont want to keep all of our old images forever, just to avoid recreating our running machines.

**Comment by tenthirtyam** [comment]
The recommended path is to use the `lifecycle` meta-argument. As previously mentioned it would look similar to the following in the `vsphere_virtual_machine` resource:

```hcl
  clone {
    template_uuid = data.vsphere_virtual_machine.template.id
  }

  lifecycle {
    ignore_changes = [
      clone[0].template_uuid,
    ]
  }
```

The above would work where source templates are updated/recreated using previously template names (e.g. via Packer) -  the name passed to `data.vsphere_virtual_machine.template.id` would remain a valid data source object and pass the new `template_uuid`, which the resource would ignore.

However, if the name no longer exists, the plan would fail since the name passed to the `vsphere_virtual_machine` data source (or `vsphere_content_library_item`) is no longer resolved/found.  There's not a method in Terraform to ignore the data source if the originating template name can no longer be found. IMHO, having `template_ignore_changes = true` would not be of benefit if the name no longer exists. 

Ryan

cc @appilon for comment and other suggested approaches.

**Comment by rene-at-dell** [comment]
appreciate the comments gents.

closing this off
