### ISSUE TITLE
Strange behavior when changing labels on linked-clone disks

### ISSUE THREAD

**Issue by plrca2** [hashicorp/terraform-provider-vsphere#1495]
```
    clone {
      template_uuid = data.vsphere_virtual_machine.source_vm.id
      linked_clone  = "true"
    } 
  
    disk {
-     label = "disk0"
+     label = data.vsphere_virtual_machine.source_vm.disks[0].label
      size = data.vsphere_virtual_machine.source_vm.disks[0].size
      thin_provisioned = data.vsphere_virtual_machine.source_vm.disks[0].thin_provisioned
      eagerly_scrub = data.vsphere_virtual_machine.source_vm.disks[0].eagerly_scrub    
      datastore_id = data.vsphere_datastore.datastore.id
    } 
```

This change causes terraform to delete the disk and create a new empty non-linked disk if the source_vm's disk[0] label is not "disk0"

The documentation notes that changing a disk's label will force the creation of a new disk, but the behavior as-is is not idempotent.

Can we make this either an error (preferred), or recreate the disk as a new linked clone?

Additionally, the plan summary for this diff shows items will be changed, but does not show any items that will be created or destroyed. Other modules with similar destructive behavior mark items as -/+ rather than ~

**Comment by tenthirtyam** [comment]
@plrca2 Would you mind recreating this issue using the new bug report template. I think we need a bit more detailed information for this issue before proceeding.

Thanks!
Ryan

**Comment by tenthirtyam** [comment]
Marking this issue as closed as more information was requested as needed.

If this issue is reproducible with the [latest](https://github.com/hashicorp/terraform-provider-vsphere/releases/latest) version of the provider, we encourage creating a new issue with more information which will assist in reproducing the issue.

Thank you!

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.
