### ISSUE TITLE
Datastore cluster data sources fail to reference group ID

### ISSUE THREAD

**Issue by wood2040** [hashicorp/terraform-provider-vsphere#1554]
### Terraform Version

1.1.3

### vSphere Provider Version

 2.0.2

### vSphere Version

vSphere 6.7 Update 3o

### Affected Resource(s)

- `vsphere_virtual_machine`

### Expected Behavior

VM is created using vsphere_datastore_cluster data source for placement

### Actual Behavior

Error: error locating datastore for VM: ServerFaultCode: The object 'vim.Datastore:group-ID' has already been deleted or has not been completely created.

### Steps to Reproduce

1. leverage the vsphere_datastore_cluster data source instead of vsphere_datastore, if you use just datastore and update your variable accordingly it works fine, this only seems to happen when specifying the name of the datastore cluster.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request.
* Please do not leave "+1" or other comments that do not add relevant new information or questions, they generate extra noise for issue followers and do not help prioritize the request.
* If you are interested in working on this issue or have submitted a pull request, please leave a comment.

**Comment by tenthirtyam** [comment]
Hi @wood2040, can you please provided a redacted version of your configuration / module for reproduction?

Ryan

**Comment by wood2040** [comment]
Sure thing, I've gone through and redacted any private info and zipped up the structure.
[hashicorp_repro.zip](https://github.com/hashicorp/terraform-provider-vsphere/files/7915257/hashicorp_repro.zip)
.

**Comment by tenthirtyam** [comment]
Try changing:

```hcl

# =================================
# ESXi Virtual Machine
# =================================

resource "vsphere_virtual_machine" "repro_vm" {
  # ....
  datastore_id  = data.vsphere_datastore_cluster.datastore_cluster.id
  # ....
}
```

to

```hcl

# =================================
# ESXi Virtual Machine
# =================================

resource "vsphere_virtual_machine" "repro_vm" {
  # ....
  datastore_cluster_id  = data.vsphere_datastore_cluster.datastore_cluster.id
  # ....
}
```

`datastore_cluster_id` should be set vs `datastore_id`.

Ryan

**Comment by wood2040** [comment]
Initial testing seems to have worked (once I verified my DSC had StorageDRS enabled). Will verify with production code. Crazy how the error sent me in a totally different direction vs. mentioning wrong usage of resource option.

**Comment by tenthirtyam** [comment]
Thanks for the update.

There are two possible ds options and it failed because it's passing a moid of the wrong type.

https://github.com/hashicorp/terraform-provider-vsphere/blob/98191889deee3b214c7a12b0f92a142226963d42/vsphere/resource_vsphere_virtual_machine.go#L80-L92

What clued me in was the error since you mentioned you were "_using_ `vsphere_datastore_cluster` _data source for placement"_

```console
Error: error locating datastore for VM: ServerFaultCode: The object 'vim.Datastore:group-ID' has already been deleted or has not been completely created.
```

It states "locating datastore" vs "locating datastore cluster"

Datastore: (`datastore_helper.go`)

https://github.com/hashicorp/terraform-provider-vsphere/blob/37fd52c400e2d7901c51c67ad683b2e7d06c6bf3/vsphere/internal/helper/datastore/datastore_helper.go#L19-L22

Datastore Cluster: (`storage_pod_helper.go`)

https://github.com/hashicorp/terraform-provider-vsphere/blob/37fd52c400e2d7901c51c67ad683b2e7d06c6bf3/vsphere/internal/helper/storagepod/storage_pod_helper.go#L22-L25

**Comment by wood2040** [comment]
It does seem obvious now that you've pointed that out. I can't thank you enough for your help on this!

**Comment by tenthirtyam** [comment]
You are very welcome, @wood2040 - _happy to help._

One you have verified that the solution is working, would you mind marking the issue as resolved/closed?

Thanks!
Ryan

**Comment by wood2040** [comment]
This is looking good, and we even found a setting that looks like we can add for any systems that were built directly to a datastore moving forward via vsphere_storage_drs_vm_override

**Comment by tenthirtyam** [comment]
@wood2040, thank you for the update!
