### ISSUE TITLE
v2.1.1 is not compatible with Terraform 0.12.31

### ISSUE THREAD

**Issue by vytas-dauksa** [hashicorp/terraform-provider-vsphere#1649]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [ ] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [ ] Do not leave "+1" or other comments that do not add relevant information or questions.
- [ ] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

0.12.31

### Terraform Provider

2.1.1

### VMware vSphere

v7

### Description

According to readme Terraform 0.12+ is supported, however since 2.1.1 I am presented with a message that v2.1.1 is not compatible with Terraform 0.12.31. Tried  v2.0.2 which works fine.

### Affected Resources

N/A

### Expected Behavior

0.12.31 is supported

### Actual Behavior

Error:
`Initializing modules...

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...

Provider "vsphere" v2.1.1 is not compatible with Terraform 0.12.31.

Provider version 1.21.1 is the latest compatible version. Select it with
the following constraint:

    version = "~> 1.21"

Terraform checked all of the plugin versions matching the given constraint:
    (any version)

Consult the documentation for this provider for more information on
compatibility between provider and Terraform versions.

Alternatively, upgrade to the latest version of Terraform for compatibility with newer provider releases.

Error: incompatible provider version`

**Comment by tenthirtyam** [comment]
Likely related to https://github.com/hashicorp/terraform-provider-vsphere/pull/1460.

**Ryan Johnson**
Staff II Solutions Architect | VMware, Inc.

**Comment by appilon** [comment]
@tenthirtyam @vytas-dauksa this is due to a bug in the release process that only affected v2.1.1 of the provider. The `protocols` header was left blank (see v2.1.1 https://registry.terraform.io/v1/providers/hashicorp/vsphere/versions). I know the issue doesn't pose a problem for Terraform 0.13+, since TF 0.13 naively downloads providers with empty protocols headers from the registry (thankfully), I guess 0.12 does not share that behavior. The resolution options are as follows

- We do have an internal ticket to backfill the registry and fix the protocols header for v2.1.1 to have the proper `protocols: ["5.0"]`, however there is blockage on being able to do that so can't provide a timeline for that
- Revert to v2.0.2 of the provider (v2.1.0 had a crash, we do not recommend using that version) and wait for v2.2.0 release of the provider. We are beginning to release the provider with better cadence so I can't commit on a date for that release, but based on the open issues in the milestone, it's reasonable to think it's soon.
- Upgrade to a newer version of Terraform, v0.12.31 was released a year ago and we generally have considered it EOL for quite some time: https://discuss.hashicorp.com/t/terraform-0-12-end-of-life/18504/2

I'll pin this issue until the registry entry is backfilled.

**Comment by appilon** [comment]
There was an issue with the naming of the binary file in release 2.1.1. Version 2.2.0 which is now release, should be compatible with Terraform 0.12 again, however we recommend upgrading to the latest version of Terraform.
