### ISSUE TITLE
Add support for OVA settings (disk, network) being considered when cloning an OVF template from content library item

### ISSUE THREAD

**Issue by mplattner** [hashicorp/terraform-provider-vsphere#1780]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Description

I use Terraform to add a content libary item (OVA) from a remote URL, as such:

```
data "vsphere_content_library" "content_library" {
  name = "ContentLib"
}

resource "vsphere_content_library_item" "content_library_item" {
  name        = "ova-linux-ubuntu-server-lts"
  description = "Ubuntu Server LTS OVF Template"
  file_url    = "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.ova"
  library_id  = data.vsphere_content_library.content_library.id
}
```

However, when I use this content library item to create a VM using `clone`, I need to explicitly specifiy blocks for `disk` and `network_interface` in the `vsphere_virtual_machine` resource. Otherwise, I get the following error(s):

```
Error: there must be at least one disk specified
Error: network_interface parameter is required when not deploying from ovf template
```

The expected behavior for me is that disk and network settings fallback to the OVA default in case I do not explicitly provide them. A workaround/solution could be to use the `vsphere_ovf_vm_template` [data type](https://registry.terraform.io/providers/hashicorp/vsphere/latest/docs/data-sources/ovf_vm_template), but I see no way to create such a data item form a content library item.

Here are the resource configs I use to create the VM:

```
data "vsphere_content_library" "content_library" {
  name = "ContentLib"
}

data "vsphere_content_library_item" "cli" {
  name       = "ova-linux-ubuntu-server-lts"
  type       = "ovf"
  library_id = data.vsphere_content_library.content_library.id
}

resource "vsphere_virtual_machine" "vmFromRemoteOvf2" {
  name                 = var.vm_name
  resource_pool_id     = data.vsphere_resource_pool.default.id

  cdrom {
    client_device = true
  }

  clone {
    template_uuid = data.vsphere_content_library_item.cli.id
  }

  vapp {
    properties = {
      "hostname"    = "ubuntu-nessustest-web1"
      "user-data" = base64encode(file("${path.module}/templates/${var.userdata_file}.yaml"))
    }
  }
}
```

### Use Case(s)

Deploy a VM from a content library item of type OVA/OVF while respecting the defaults that the OVA/OVF sets for disks, networks etc.

**Comment by mplattner** [comment]
To me it seems like #1435 is related. Btw, I also see the behavior described in #1435 - the NIC is removed if not explicitly defined via `network_interface`.

**Comment by WannaBeGeekster** [comment]
Typically when you are deploying from a template you would create a data object with the template and then you can use the data object properties to define the important variables where the defaults do not work. IE:

`data "vsphere_virtual_machine" "template" {
  name  = var.template_name
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  name = var.vm_name
  ...
   scsi_type = data.vsphere_virtual_machine.template.scsi_type
`
I do not currently see a way to create a data object from an OVA/OVF stored in a Content Library. As a matter of fact it doesn't appear as if the vsphere_ovf_vm_template conforms to the standards of referencing a data object in general. It appears as if you specify settings that should be specified when you are creating a the VM instead of when referencing an object.  Doesn't make sense why I would need to specify the following parameters when setting up a simple data object at all:

resource_pool_id
datastore_id
host_system_id
ovf_network_map

Those items should be specified in a resource not in a data object. Typically those values are gleaned from previous data object creation in the first place.

The vsphere_ovf_vm_template should allow you to specify a library_id for the "path to the OVF" in addition to a remote_ovf_url or local_ovf_path.

The library_id works just fine if using the clone method to create a VM from an OVF.  Not sure why there is also the ovf_deploy in addition to clone.  I realize there are additional options available in the ovf_deploy but the only one that seems significant is the remote_ovf_url since you are obviously not going to be able to return a UUID of a URL. I do realize that the ovf_deploy section is attempting to comply to the vSphere API.

Thanks for all of your hard work. I realize this is a complicated thing to fit together. But a data object should act as a data object and not something you pass settings in to for use in a resource. Those should be specified in the resource. Additionally if I can store an OVA/OVF in a content library, then I need to be able to create a data object using a referential link to the content library item ID.
