### ISSUE TITLE
Second CD-ROM device is not showing in Windows VMs

### ISSUE THREAD

**Issue by cgiraldo** [hashicorp/terraform-provider-vsphere#1912]
### Community Guidelines

- [X] I have read and agree to the [HashiCorp Community Guidelines ](https://www.hashicorp.com/community-guidelines).
- [X] Vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue initial description to help the maintainers prioritize.
- [X] Do not leave "+1" or other comments that do not add relevant information or questions.
- [X] If you are interested in working on this issue or have submitted a pull request, please leave a comment.

### Terraform

v1.3.7

### Terraform Provider

v2.4.0

### VMware vSphere

v8.0.0

### Description

We include two cd-rom devices to mount two different .iso files from a datastore.

We expect to have unit D: and unit E: in windows. But only unit D: is available.

Device Manager in Windows only shows 1 CD-ROM Drive.

The problem happens when setting cdrom1 to ide0:0 and cdrom2 to ide0:1.

If we use different ides (e.g. ide0:0 and ide1:0) both cd-roms are shown in windows.

Is it possible to add the option to set the device ide in the cdrom description?

### Affected Resources or Data Sources

`resource/vsphere_virtual_machine`

### Terraform Configuration

```hcl
....
cdrom {
    datastore_id = data.vsphere_datastore.iso_datastore.id
    path         = "isos/iso1.iso"
}

cdrom {
    datastore_id = data.vsphere_datastore.iso_datastore.id
    path         = "isos/iso2.iso"
}
....
```

### Debug Output

No debug output as resource is correctly deployed.

### Expected Behavior

We expect to have unit D: and unit E: in Windows.

### Actual Behavior

Only unit D: is available.

### Steps to Reproduce

Declare a `vsphere_virtual_machine` with two CD-ROMs for a Windows OS.

### References

#1164

**Comment by tenthirtyam** [comment]
Hi @cgiraldo 👋 - I realize that this issue is over a year old, but I wanted to check in.

If you use the following:

```hcl
....
cdrom {
    datastore_id = data.vsphere_datastore.iso_datastore.id
    path         = "isos/iso1.iso"
}

cdrom {
    datastore_id = data.vsphere_datastore.iso_datastore.id
    path         = "isos/iso2.iso"
}
....
```

... then the first CD-ROM will be assigned to `ide0:0` per the provider implementation (forced default) and the additional CD-ROM would be assigned to a SATA controller like `SATA0:0` (like in the UI, etc. This does work in the provider.

Today, you can not set the `device_address` that you'd see in the state; however, this is a good areas for enhancement that could be extended from the exisiting enhancement request (#1354).

Example:

```json
"cdrom": [
              {
                "client_device": false,
                "datastore_id": "datastore-18077",
                "device_address": "sata:0:0",
                "key": 16000,
                "path": "iso/foo/bar.iso"
              }
            ],
```

Ideally, the provider should support a configuration such as:

```hcl
cdrom {
    datastore_id   = data.vsphere_datastore.datastore_iso.id
    device_address = "ide0:0"
    path           = "iso/foo/bar.iso"
}
cdrom {
    datastore_id   = data.vsphere_datastore.datastore_iso.id
    device_address = "ide0:0"
    path           = "iso/bar/foo.iso"
}
```

or

```hcl
cdrom {
    datastore_id   = data.vsphere_datastore.datastore_iso.id
    device_address = "sata0:0"
    path           = "iso/foo/bar.iso"
}
cdrom {
    datastore_id   = data.vsphere_datastore.datastore_iso.id
    device_address = "sata0:1"
    path           = "iso/bar/foo.iso"
}
```

etc...

This said, if the VM is imported with existing CD-ROMs, it will accept these if the imported configuration uses two ide as you have mentioned.

**Ryan Johnson**
Distinguished Engineer, VMware by Broadcom
