### ISSUE TITLE
Post-migration: Error applying plan due to 403 from tagging API

### ISSUE THREAD

**Issue by vancluever** [hashicorp/terraform-provider-vsphere#294]
This seems to only be happening _very_ sporadically and I'm wondering if it has to do with a race condition  in the order of things being applied (possibly that the 403 is not due to actually not being authorized but some state post-migration).

Migration succeeds, and then vSphere kicked back this:

```
Error: Error applying plan:

1 error(s) occurred:

* vsphere_virtual_machine.example_virtual_machines[1]: 1 error(s) occurred:

* vsphere_virtual_machine.example_virtual_machines.1: Get unexpected status code: 403: call failed: Error response from vCloud Suite API: {"type":"com.vmware.vapi.std.errors.unauthorized","value":{"messages":[]}}
```

Further plans return no changes, so there was no issues with the migration.

Possible resolution may be to add a waiter for this operation in the VM resource with a very short retry period, just enough to rule out any post-update transient issues.

## Important Factoids

This is happening in the post-update `Read` cycle, more than likely. vMotion is the _very_ last thing that's handled during the update phase.

**Comment by deberon** [comment]
This is the same error I was receiving in #239 but came when I was creating a Folder.

**Comment by vancluever** [comment]
@deberon yeah, this is a good point!

I wonder if maybe a general backoff would be a good idea then.

**Comment by palesiak** [comment]
+1 on this bug... ran into it today fairly randomly (and for the first time between probably thousands of terraform runs). Unfortunately, did not have TF_LOG=1 enabled, and when I retried it went away. Would be nice to see some sort of one shot retry, perhaps

**Comment by failshell** [comment]
+1

**Comment by dmitri-s** [comment]
I have this error everytime I am running `terraform apply`. Does anyone know why this is happening?

**Comment by ajureeruja** [comment]
+1 I'm running into this every time I run `terraform apply`.  Any updates?

`2020-07-29T14:46:24.436-0400 [DEBUG] plugin.terraform-provider-vsphere_v1.15.0_x4: 2020/07/29 14:46:24 [DEBUG] Reading tags for object "vm-15443"
2020-07-29T14:46:24.442-0400 [DEBUG] plugin.terraform-provider-vsphere_v1.15.0_x4: 2020/07/29 14:46:24 [DEBUG] Tags for object "vm-15443":
2020/07/29 14:46:24 [DEBUG] vsphere_virtual_machine.linux[1]: apply errored, but we're indicating that via the Error pointer rather than returning it: Get unexpected status code: 403: call failed: Error response from vCloud Suite API: {"value":{"messages":[]},"type":"com.vmware.vapi.std.errors.unauthorized"}
2020/07/29 14:46:24 [ERROR] <root>: eval: *terraform.EvalApplyPost, err: Get unexpected status code: 403: call failed: Error response from vCloud Suite API: {"value":{"messages":[]},"type":"com.vmware.vapi.std.errors.unauthorized"}
2020/07/29 14:46:24 [ERROR] <root>: eval: *terraform.EvalSequence, err: Get unexpected status code: 403: call failed: Error response from vCloud Suite API: {"value":{"messages":[]},"type":"com.vmware.vapi.std.errors.unauthorized"}`

**Comment by aareet** [comment]
@ajureeruja can you share:

### Terraform Version

### vSphere Provider Version

**Comment by ajureeruja** [comment]
Terraform version: 0.12.18
vSphere Provider Version: v1.15.0

**Comment by aareet** [comment]
@ajureeruja do you have a minimal TF config that you can share that reliably reproduces this? We've had difficulty recreating this issue when we have looked before.

**Comment by ajureeruja** [comment]
Actually, to be more specific.  If I loop the apply command, it may succeed after a few minutes, or may take hours.  It does succeed sometimes, but rarely.

**Comment by ajureeruja** [comment]
Here is a minimal TF config that reproduces the issue for me.

```
provider "vsphere" {
  user                 = var.vsphere_user
  password             = var.vsphere_password
  vsphere_server       = var.vsphere_server
  version              = "1.15.0"

  # If you have a self-signed cert
  allow_unverified_ssl = true
}

data "vsphere_datacenter" "dc" {
  name = var.vvm_datacenter
}

data "vsphere_datastore" "datastore" {
  name          = var.vvm_datastore
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_resource_pool" "pool" {
  name          = var.vvm_pool
  datacenter_id = data.vsphere_datacenter.dc.id
}

data "vsphere_network" "network" {
  name          = var.vvm_network
  datacenter_id = data.vsphere_datacenter.dc.id
}

resource "vsphere_virtual_machine" "vm" {
  name             = "terraform-test"
  resource_pool_id = data.vsphere_resource_pool.pool.id
  datastore_id     = data.vsphere_datastore.datastore.id
  folder           = var.vvm_folder

  wait_for_guest_net_timeout  = -1
  wait_for_guest_net_routable = false
  wait_for_guest_ip_timeout   = -1

  num_cpus = 2
  memory   = 1024
  guest_id = "centos64Guest"

  network_interface {
    network_id = data.vsphere_network.network.id
  }

  disk {
    label = "disk0"
    size  = 20
  }
}

variable "vsphere_user" {
  type        = string
}

variable "vsphere_password" {
  type        = string
}

variable "vsphere_server" {
  type        = string
}

variable "vvm_datacenter" {
  type        = string
}

variable "vvm_datastore" {
  type        = string
}

variable "vvm_pool" {
  type        = string
}

variable "vvm_network" {
  type        = string
}

variable "vvm_folder" {
  type        = string
}
```

**Comment by bill-rich** [comment]
Please try using the  `persist_session` option in the provider block. This looks like an issue with maxing out the number of allowed sessions.
