### ISSUE TITLE
Add support in `d/virtual_machine` to return network adapters and mac addresses

### ISSUE THREAD

**Issue by gvcgael** [hashicorp/terraform-provider-vsphere#809]
Hello,

It would be great if the `data` `virtual_machine` could return the mac addresses of the network adapters of the VM : 

https://www.terraform.io/docs/providers/vsphere/d/virtual_machine.html

At the moment, we have to set the `mac addresses` hardcoded, but its not possible since of this bug  : https://github.com/terraform-providers/terraform-provider-vsphere/issues/488

**Comment by aareet** [comment]
Relates to #488

**Comment by azbpa** [comment]
Same requirement here. Any chance this gets implemented?

**Comment by arizvisa** [comment]
It seems that the vsphere_virtual_machine data source needs another entry added to its schema. Either it's the following attribute in the schema.
https://github.com/hashicorp/terraform-provider-vsphere/blob/814675b5da80f286a082664d22455b7c8264134a/vsphere/data_source_vsphere_virtual_machine.go#L135-L140

Or the field could be added to the schema here:
https://github.com/hashicorp/terraform-provider-vsphere/blob/814675b5da80f286a082664d22455b7c8264134a/vsphere/virtual_machine_guest_structure.go#L15-L30

In the `buildAndSelectGuestIPs()` function (https://github.com/hashicorp/terraform-provider-vsphere/blob/814675b5da80f286a082664d22455b7c8264134a/vsphere/virtual_machine_guest_structure.go#L43
), the addresses are aggregated into the `addrs` list from both the `v4net2addrs` and `v6net2addrs` maps and then set to "guest_ip_addresses" at the bottom of the function.

https://github.com/hashicorp/terraform-provider-vsphere/blob/814675b5da80f286a082664d22455b7c8264134a/vsphere/virtual_machine_guest_structure.go#L123-L128

Both of those maps are keyed by `n.DeviceConfigId` which should be the hwaddr for each device, so it seems like all one would need to do would be to aggregate each of the keys into another list that would then be set directly into the schema similar to the "guest_ip_addresses" field.

As this issue was tagged with "help wanted", it might be faster for someone to contribute and submit a PR.

**Comment by appilon** [comment]
This actually went out in v2.0.0 of the provider

**Comment by arizvisa** [comment]
I think it was #1274?
