### ISSUE TITLE
FEATURE REQUEST - Dynamic Datasources

### ISSUE THREAD

**Issue by stobias123** [hashicorp/terraform-provider-vsphere#937]
I'm using this provider more and more lately. Support has gotten better, and it really helps align vmware infrastructure with the SDDC ideology vmware is pushing, and thus infrastructure as code through terraform.

However, the data sources from this provider are lacking when compared to providers like `aws` or `gcp` or any cloud provider.

I would like to dynamically retrieve available resources from vmware using a `filter` similar to 
[aws_ami](https://www.terraform.io/docs/providers/aws/d/ami.html) datasource and [aws_subnet_ids](https://www.terraform.io/docs/providers/aws/d/subnet_ids.html) data source.

VMWare tags should be sufficient for filters, and would really help push this provider (and vmware) to the next level if such functionality was added.

### Suggested First Resource(s)

Please list the resources as a list, for example:
- `vsphere_virtual_machine` - for finding templates.
- `vsphere_datastore_cluster ` - for finding datastores via tags (eg. SRM tag :) )

### Example
This is how I'd imagine the `vsphere_virtual_machine` working.
```hcl
data "vsphere_virtual_machine" "rhel_template_prod" {
  datacenter_id = "${data.vsphere_datacenter.datacenter.id}"
  most_recent      = true
  name_regex       = "^GOLD.+"

  filter {
    key   = "operating_system"
    values = ["rhel"]
  }
}
```

### Important Factoids

Other cloud providers have this functionality. The lack of dynamic datasources is holding this provider back.

**Comment by bill-rich** [comment]
Hi @stobias123! I like the idea of adding support for this type of filtering as it could help make it easier to find an object based on something besides the name. We'd need to look a bit more into it to see if there would be any other implications to making a change like this. Best case though, we'd be able to do something like this in the 2.0 release (which doesn't have a planned date yet), since it would be a breaking change to existing configurations.

I'll get a tag on this to look at when we're looking at what to work on and include in that release. Thank you for the suggestion!

**Comment by minhluantran017** [comment]
This is exactly the feature that I'm looking for now. Waiting for it to be supported.

**Comment by stobias123** [comment]
@bill-rich  - I saw this was removed from v2.0 - was it decided not to work on this feature?

**Comment by bill-rich** [comment]
@stobias123 It is actually nearly done. Though it is implemented slightly different. It should make it into the release this week or next.

**Comment by bill-rich** [comment]
Completed in #1103
